import os
from flask import Flask
from google.cloud import storage
import pandas as pd
import polars as pl
import datetime as dt

app = Flask(__name__)

#replace with secret on deploy
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = 'placeholder'


@app.route('/')
def print_hi(name):
    # Use a breakpoint in the code line below to debug your script.
    return f'Hi, {name}'  # Press ⌘F8 to toggle the breakpoint.


def read_bucket(bucket_name, file_name):
    client = storage.Client()

    bucket = client.get_bucket(bucket_name)
    blob = bucket.blob(file_name)
    df = pd.read_csv(blob.open('rb'))
    return df


def write_bucket(bucket_name, file_name, df):
    client = storage.Client()
    bucket = client.get_bucket(bucket_name)
    bucket.write_blob(file_name, df)

def test1() -> pl.LazyFrame:
    """
    Write a function that:
    Accepts video_stream_df as input.
    Returns a filtered DataFrame that includes only the videos which:

    Have more than 1,000,000 views
    Were released in the last 6 years (relative to the current year)
    Reorders the columns in the following format:

    duration, genre, release_year, title, video_id, view_count
    Sort the data using column duration
    """
    data = {
        "video_id": [1, 2, 3, 4, 5],
        "title": ["Amazing Adventure", "Sci-fi World", "Mysterious Island", "Uncharted Realms", "Journey to the Stars"],
        "genre": ["Action", "Sci-fi", "Drama", "Action", "Sci-fi"],
        "release_year": [2020, 2018, 2022, 2019, 2021],
        "duration": [120, 140, 115, 134, 128],
        "view_count": [2500000, 800000, 1500000, 3200000, 1100000],
    }

    video_stream_df = pl.LazyFrame(data=data)
    print(video_stream_df.collect())

    output_df = test(video_stream_df)
    print(output_df.collect())
    return video_stream_df.filter(
        pl.col("view_count") > 1000000,
        pl.col("release_year") >= dt.datetime.strptime("2020", "%Y").year- 7,
    ).select(
        "duration",
        "genre",
        "release_year",
        "title",
        "video_id",
        "view_count"
    ).sort('duration')

def test3()->pl.LazyFrame:

    prop_properties = pl.LazyFrame({
    "property_id": [1,2,3,4,5],
    "landlord_id": [101,101,102,103,103],
    "property_type": ["Apartment","Condo","House","Apartment","Condo"],
    "rent": [1500, 1200, 2000, 1800, 1000],
    "square_feet":[1000, 800, 1500, 1200, 700],
    "city":["Seattle", "Seattle", "Bellevue", "Redmond", "Redmond"]
    })

    prop_landlords = pl.LazyFrame({
    "landlord_id": [101,102,103,104],
    "first_name": ["John", "Jane", "Bob", "Mary"],
    "last_name": ["Smith", "Doe", "Johnson", "Williams"]
    })

    prop_landlords = prop_landlords.select(
        pl.col("landlord_id"),
        (pl.col("first_name") + " " + pl.col("last_name")).alias("landlord_name")
    )

    df = prop_landlords.join(
        prop_properties,
        on="landlord_id",
        how="inner"
    ).group_by(
        pl.col("landlord_id"),
        pl.col("landlord_name")
    ).agg(pl.col("rent").sum())
    print(df.collect())
    """
    Return a summary DataFrame/table with the following structure:

    Column Name	Data Type	Description
    landlord_id	Integer	Unique ID of the landlord
    landlord_name	String	Full name of the landlord (first_name + ' ' + last_name)
    total_rental_income	Float	Total rental income generated by all properties owned

    Eliminate any duplicate rows in the input data before processing.
    Join both datasets using the landlord_id.
    Only include landlords who have at least one property.
    Sum the rent across all properties owned by a landlord.
    Construct the landlord_name as: first_name + ' ' + last_name.
    :return:
    """

def test4()->pl.LazyFrame:
    products = pl.LazyFrame({
        "product_id": [1, 2, 3, 4, 5, 6, 7, 8, 9],
        "category": ["A", "A", "A", "B", "B", "B", "C", "C", "C"],
        "product_name": ["product1", "product2", "product3",
                         "product4", "product5", "product6",
                         "product7", "product8","product9"],
    })

    sales = pl.LazyFrame({
        "sale_id": [1, 2, 3, 4, 5, 6, 7, 8, 9],
        "product_id": [1, 2, 3, 4, 5, 6, 7, 8, 9],
        "quantity": [10, 8, 12, 5, 3, 7, 15, 10, 8],
        "revenue": [100, 120, 180, 50, 30, 70, 150, 100, 80],
    })
    """
    Your task is to write a function or SQL query that returns the top 3 selling 
    products in each product category, ranked by revenue (highest first).

    The ranking must:

    Be based on total revenue per product.
    Use dense ranking — i.e., no gaps in the ranking sequence if there's a tie.
    Output only the top 3 products per category.
    :return:
    """
    df = sales.join(products, on="product_id").select(
        pl.col("category"),
        pl.col("product_name"),
        pl.col("revenue"),
        pl.col("revenue")
        .rank("dense", descending=True)
        .over("category")
        .alias("rank"),
    ).sort("category", "rank").filter(
        pl.col("rank") <= 3)
    return print(df.collect())

def test5()->pl.LazyFrame:

    df = pl.LazyFrame({
        "user_id": [445, 742, 445, 742, 648, 742, 445, 742, 648],
        "event_id": [7765, 6558, 3634, 1374, 3124, 4521, 7563, 8541, 9512],
        "event_type": ['sign-in', 'sign-in', 'like', 'comment', 'like', 'like', 'comment', 'sign-in', 'comment'],
        "event_date": ["2022-06-30 12:00:00", "2022-06-03 12:00:00", "2022-06-05 12:00:00",
                       "2022-06-05 12:00:00", "2022-06-18 12:00:00", "2022-07-01 12:00:00",
                       "2022-07-02 12:00:00", "2022-07-05 12:00:00", "2022-07-15 12:00:00"]
    })
    df = df.select(
        pl.col("user_id"),
        pl.col("event_id"),
        pl.col("event_type"),
        pl.col("event_date").str.to_datetime("%Y-%m-%d %H:%M:%S").alias("formatted_date"),
    )
    df = df.select(
        pl.col("user_id"),
        pl.col("event_id"),
        pl.col("event_type"),
        pl.col("formatted_date").dt.year().alias("year"),
        pl.col("formatted_date").dt.month().alias("month"),
    )
    """
    Assume you're given a table containing information on user actions. 
    Write a query to obtain the number of monthly active users (MAUs) in July 2022, 
    including the month in numerical format ("1, 2, 3").

    Definition of Active User: An active user is defined as a user who has performed actions such as 'sign-in', 
    'like', or 'comment' in both the current month (July 2022) and the previous month (June 2022).
    
    :return:
    """

    df = (df.filter(
        pl.col("event_type").is_in(['sign-in', 'like', 'comment']),
        pl.col("month") == 7)
    .group_by(
        pl.col("month"),
    ).agg(
        pl.col("user_id").n_unique().alias("monthly_active_users"),
    ))

    return print(df.collect())

def test6()->pl.LazyFrame:
    df = pl.LazyFrame({
        "user_id": [445, 742, 445, 742, 648, 742, 445, 742, 648],
        "event_id": [7765, 6558, 3634, 1374, 3124, 4521, 7563, 8541, 9512],
        "event_type": ['sign-in', 'sign-in', 'like', 'comment', 'like', 'like', 'comment', 'sign-in', 'comment'],
        "event_date": ["2022-06-30", "2022-06-03", "2022-06-29",
                       "2022-06-05", "2022-06-18", "2022-07-01",
                       "2022-07-02", "2022-07-05", "2022-07-15"]
    })
    df = df.with_columns(
        pl.col("event_date").str.to_date("%Y-%m-%d").alias("formatted_date"),
    ).sort("user_id","formatted_date")
    df = df.select(
        pl.col("user_id"),
        pl.col("formatted_date"),
        pl.col("formatted_date").shift(1).over("user_id").alias("lag"),
        pl.col("formatted_date").shift(-1).over("user_id").alias("lead"),
        pl.col("formatted_date").rank("dense", descending=False).over("user_id").alias("rank"),
    )
    df = df.with_columns(
        rank_offset="-" + pl.col("rank").cast(pl.String) + "d"
    )
    df = df.with_columns(
        island = pl.col("formatted_date").dt.offset_by(pl.col("rank_offset"))
    )
    df = df.with_columns(
        island_count =
        pl.col("island").cum_count().over(
            pl.col("island"), pl.col("user_id")
        )
    )
    grouped = df.select(
        pl.col("user_id"),
        pl.col("formatted_date"),
        pl.col("rank_offset"),
        pl.col("island"),
        pl.col("island")
        .rank("dense" , descending=False)
        .over("user_id")
        .alias("island_group"),
    )

    return print(df.collect())

def test()->pl.LazyFrame:



    return print(df.collect())

if __name__ == '__main__':
    print(print_hi('PyCharm'))

    bucket_name = 'anthony-source'
    file_name = 'test.csv'

    test()
    #df = read_bucket(bucket_name, file_name)
    #write_bucket(bucket_name, file_name, df)
    #port = int(os.environ.get('PORT', 8080))
    #app.run(host='0.0.0.0', port=port)

# See PyCharm help at https://www.jetbrains.com/help/pycharm/
